[package]
name = "macroquad_tamagotchi"
version = "0.1.0"
edition = "2021"

[package.metadata.android]
label = "MACROQUAD TAMOGOTCHI"
min_sdk_version = 26
target_sdk_version = 28
build_targets = ["armv7-linux-androideabi"]

[dependencies]
# macroquad = { path = "../macroquad" }
# macroquad = "0.4"
macroquad = { git = "https://github.com/not-fl3/macroquad", rev = "b6f43bb868e776540ef8ebebd10299f1aac1c06c"}

geometric_algebra = "0.3.0"
ttf-parser = { version = "0.14.0" }

glam = {version = "0.27.0", features = ["scalar-math"] } # to conform to macroquad
euclid = "0.22.7"
# lottie = {path="../lottie-rs/crates/lottie"}
# lottie = {git = "https://github.com/birhburh/lottie-rs", branch = "temp_changes"}
# nanoserde = {version = "0.2.0-beta.0", default-features = false, features = ["std", "json"]}
# nanoserde = {path="../nanoserde", default-features = false, features = ["std", "json"]}
nanoserde = {git = "https://github.com/not-fl3/nanoserde", default-features = false, features = ["std", "json"]}
# serde = { version = "1.0", features = ["derive"] }
# serde_json = "1.0"

# dependencies for ochre code
usvg = "0.44.0"
tiny-skia-path = "0.11.4"

# dependencies for pathfinder code
bitflags = "1.0"
half = "1.5"

[dependencies.pathfinder_geometry]
version = "0.5.1"

[dependencies.pathfinder_simd]
version = "0.5.4"

[dependencies.pathfinder_color]
version = "0.5.0"

[dependencies.image]
version = "0.23"
default-features = false
features = ["png"]

[patch.crates-io]
# miniquad = { path="../miniquad", features = ["log-impl"] }
miniquad = { git = "https://github.com/birhburh/miniquad", branch = "clear_vertex_attributes_fix"}
# miniquad = { git = "https://github.com/not-fl3/miniquad" }

[profile.release]
lto = true
panic = 'abort'
opt-level = 3
overflow-checks = false
debug-assertions = false
rpath = false
codegen-units = 1
strip = true
